name: Python package

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: pytest tests.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
        # A list of JUnit XML files, directories containing the former, and wildcard
        # patterns to process.
        # See @actions/glob for supported patterns.
        path: junit/test-results-${{ matrix.python-version }}.xml

        # Add a summary of the results at the top of the report
        # Default: true
        summary: true

        # Select which results should be included in the report.
        # Follows the same syntax as
        # `pytest -r`
        # Default: fEX
        display-options: fEX

        # Fail the workflow if no JUnit XML was found.
        # Default: true
        fail-on-empty: true
